### ISSUE TITLE
Disable "Add me to this group" button for user who is already part of it and show right side the list of group already assigned to user 

### ISSUE THREAD

**Issue by iamitprakash** [Real-Dev-Squad/website-dashboard#424]
Based on Task https://github.com/Real-Dev-Squad/website-dashboard/issues/398

On group page, once user is added themselves in one group then "Add me to this group" should be disabled for that group and in right side show right side the list of group already assigned to user

**Comment by bksh05** [comment]
I am interested in this. I recently worked on the flow. 
Once assigned I will come up with additional details and start working on this.

**Comment by bksh05** [comment]
As part of this issue, 
1. we need to add a panel on the right that displays a list of groups in which the user is already a member.
2. Disable the "Add me to this group" button if the user is already part of the group.

Questions:
1. Can the user select any group from the right panel? If yes, what happens when the user selects it?
2. Does the left panel show all the groups or only the groups the user is not a part of?
3. When the user joins a group, does it create a new entry in the right panel instantaneously, or does the user have to refresh the page to see the group?

Suggestion: 
Instead of the right panel, can we just add a quick filter button below the search box "My Groups" which on clicking will only show the list of groups that I am part of in the left panel and clicking again will show all the groups.

**Comment by bksh05** [comment]
Hi @ankushdharkar and @iamitprakash,

Could we add something called "Quick Filters" like in this picture?

When you press "My Groups," it should only show the groups you're in. Press it again, and all the groups will come back.

Also, if you click on a group you're already in, then "Add me to this group" button will stay in a disabled state. 

By the way, I'll make the quick filter button look like a small pill that switches. Ignore how it looks in the picture.


![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/27444637/a4be4e05-e733-4ff4-8558-9be6e0155880)

**Comment by bksh05** [comment]
As discussed, this page will comprise three distinct sections:

Left Panel: Displays all groups that the current user is not a part of.
Right Panel: Presents all groups of which the current user is a member.
Middle Panel: Contains a button labeled "Add me to this group." The button will be activated only when a non-member group is selected.

**Comment by bksh05** [comment]
After going through the dashboard code I have going to use the below steps to show the right panel. 

1. Refactor the existing dashboard code so that we can reuse the code of the left panel for the new right panel
2. The API changes will add an extra parameter to each group showing if the current user is part of the group or not. The issue for that is [here](https://github.com/Real-Dev-Squad/website-backend/issues/1388).
3. The UI will separate the groups for the left panel and right panel and show the groups in the UI.
4. The experience of the right panel will be the same as the left panel.
